### ISSUE TITLE
npm start not working 

### ISSUE THREAD

**Issue by PoseidonSaan** [ollelauribostrom/rebus#932]
## Expected Behavior
should start the local server and launch the app

...

## Actual Behavior
> rebus@1.0.0 start
> webpack-dev-server --mode development

(node:9424) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
i ｢wds｣: Project is running at http://localhost:3000/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\ojasv\rebus\dist
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\Users\ojasv\rebus\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\Users\ojasv\rebus\node_modules\webpack\lib\NormalModule.js:386:16)
    at handleParseError (C:\Users\ojasv\rebus\node_modules\webpack\lib\NormalModule.js:434:10)
    at C:\Users\ojasv\rebus\node_modules\webpack\lib\NormalModule.js:466:5
    at C:\Users\ojasv\rebus\node_modules\webpack\lib\NormalModule.js:327:12
    at C:\Users\ojasv\rebus\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (C:\Users\ojasv\rebus\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at Array.<anonymous> (C:\Users\ojasv\rebus\node_modules\loader-runner\lib\LoaderRunner.js:202:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

...

## Steps to Reproduce the Problem

1. Step 1..
2. Step 2..
3. Step 3..

## Specifications

- Browser: google chrome

**Comment by its-kumar-yash** [comment]
Hey @PoseidonSaan, I want to solve this issue please assign this to me. Thanks

**Comment by wchetan** [comment]
Hey @PoseidonSaan, [this](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported) thread worked for me. 
I ran `set NODE_OPTIONS=--openssl-legacy-provider ` in command prompt & It worked. Hope it helps : ).

**Comment by Gourav2609** [comment]
> Hey @PoseidonSaan, I want to solve this issue please assign this to me. Thanks



> Hey @PoseidonSaan, [this](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported) thread worked for me. I ran `set NODE_OPTIONS=--openssl-legacy-provider ` in command prompt & It worked. Hope it helps : ).

I tried this but this is not working for me

**Comment by sarmadhamdani02** [comment]
Hi! 👋
I am also facing the same issue 😟
Can someone suggest the possible solution?

**Comment by LucasAlmeida-jpg** [comment]
Hi guys
I am also facing the same issue, any tips?

**Comment by vichustephen** [comment]
Hey @PoseidonSaan This issue occurs when you use node version 16+. As @wchetan  mentioned you can use the command. Assign this issue to me I will update package.json
